from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
import base64
from datetime import datetime

router = APIRouter()

class ReportRequest(BaseModel):
    prediction_id: str
    disease_type: str
    prediction: str
    confidence: str
    risk_level: str
    guidance: str

@router.post("/generate")
async def generate_report(request: ReportRequest):
    # Simple simulated report generation returning a text summary for now
    # In a full setup, this would use pdfkit or reportlab to create a real PDF
    report_content = f"""
    MEDICAL DIAGNOSTIC REPORT
    ========================
    Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
    
    Diagnosis Type: {request.disease_type.upper()}
    AI Prediction: {request.prediction}
    Confidence Level: {request.confidence}
    Risk Assessment: {request.risk_level}
    
    AI GUIDANCE & RECOMMENDATIONS:
    -----------------------------
    {request.guidance}
    
    Disclaimer: This report is generated by an AI system (VitalsAI) and should be reviewed by a medical professional.
    """
    
    # Simulate a file URL or base64
    encoded_report = base64.b64encode(report_content.encode()).decode()
    
    return {
        "message": "Report generated successfully",
        "report_data": f"data:text/plain;base64,{encoded_report}",
        "filename": f"Report_{request.disease_type}_{datetime.now().strftime('%Y%m%d')}.txt"
    }
